[package]
name = "stripe"
version = "0.2.0"
authors = ["Mike Berry <mikethetike@tari.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
